"""empty message

Revision ID: 05b665d05cfd
Revises: f26ce4aee250
Create Date: 2021-08-18 18:32:43.806979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b665d05cfd'
down_revision = 'f26ce4aee250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneeze_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player1_time', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('player2_time', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneeze_game', schema=None) as batch_op:
        batch_op.drop_column('player2_time')
        batch_op.drop_column('player1_time')

    # ### end Alembic commands ###
