"""empty message

Revision ID: 2dc6a74f8448
Revises: c7ff3c67c058
Create Date: 2021-08-18 00:45:17.795911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc6a74f8448'
down_revision = 'c7ff3c67c058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multi_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createTime', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multi_room', schema=None) as batch_op:
        batch_op.drop_column('createTime')

    # ### end Alembic commands ###
