"""empty message

Revision ID: 318f8ab80f75
Revises: 
Create Date: 2021-08-09 20:35:19.234300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318f8ab80f75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itemImg', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_book', schema=None) as batch_op:
        batch_op.drop_column('itemImg')

    # ### end Alembic commands ###
