"""empty message

Revision ID: 338df913cbf6
Revises: c23954660d11
Create Date: 2021-08-20 13:29:42.521603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338df913cbf6'
down_revision = 'c23954660d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('descript', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('p_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_book', schema=None) as batch_op:
        batch_op.drop_column('p_type')
        batch_op.drop_column('descript')
        batch_op.drop_column('food')

    # ### end Alembic commands ###
