"""empty message

Revision ID: 3bdb97b5431d
Revises: af7f2fd8626b
Create Date: 2021-08-24 16:52:31.042259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bdb97b5431d'
down_revision = 'af7f2fd8626b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('growing_select', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_status', schema=None) as batch_op:
        batch_op.drop_column('growing_select')

    # ### end Alembic commands ###
