"""empty message

Revision ID: 51420cfb28ad
Revises: 6af26d4f8df3
Create Date: 2021-08-12 18:46:28.470676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51420cfb28ad'
down_revision = '6af26d4f8df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('value')

    # ### end Alembic commands ###
