"""empty message

Revision ID: 75f1196a4639
Revises: 51420cfb28ad
Create Date: 2021-08-13 10:44:05.775785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f1196a4639'
down_revision = '51420cfb28ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kakaoKey', sa.String(length=90), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_kakaoKey'), ['kakaoKey'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_kakaoKey'), type_='unique')
        batch_op.drop_column('kakaoKey')

    # ### end Alembic commands ###
