"""empty message

Revision ID: 8e822e20fae5
Revises: a595f505f7fa
Create Date: 2021-08-17 13:15:59.805495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e822e20fae5'
down_revision = 'a595f505f7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneeze_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player1', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('player2', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneeze_game', schema=None) as batch_op:
        batch_op.drop_column('player2')
        batch_op.drop_column('player1')

    # ### end Alembic commands ###
