"""empty message

Revision ID: 9b82a16484bc
Revises: 318f8ab80f75
Create Date: 2021-08-11 12:19:26.242748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b82a16484bc'
down_revision = '318f8ab80f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hatchingTimer', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_status', schema=None) as batch_op:
        batch_op.drop_column('hatchingTimer')

    # ### end Alembic commands ###
