"""empty message

Revision ID: acf6d4073216
Revises: 05b665d05cfd
Create Date: 2021-08-19 18:52:40.846323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf6d4073216'
down_revision = '05b665d05cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hatching_egg', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_status', schema=None) as batch_op:
        batch_op.drop_column('hatching_egg')

    # ### end Alembic commands ###
