"""empty message

Revision ID: af7f2fd8626b
Revises: 0d08a8c9bd5d
Create Date: 2021-08-21 17:55:53.899899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7f2fd8626b'
down_revision = '0d08a8c9bd5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('growing_pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('timer', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('growing_pet', schema=None) as batch_op:
        batch_op.drop_column('timer')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
