"""empty message

Revision ID: c23954660d11
Revises: be785dc4b32c
Create Date: 2021-08-20 13:13:27.778685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23954660d11'
down_revision = 'be785dc4b32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=200), nullable=False))
        batch_op.drop_column('food')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('img')

    # ### end Alembic commands ###
