"""empty message

Revision ID: c7ff3c67c058
Revises: 8e822e20fae5
Create Date: 2021-08-17 13:19:29.544344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ff3c67c058'
down_revision = '8e822e20fae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneeze_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('player2', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneeze_game', schema=None) as batch_op:
        batch_op.drop_column('player2')
        batch_op.drop_column('player1')

    # ### end Alembic commands ###
