"""empty message

Revision ID: c900b0cd7771
Revises: 2dc6a74f8448
Create Date: 2021-08-18 13:55:15.416129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c900b0cd7771'
down_revision = '2dc6a74f8448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneeze_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player1_power', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneeze_game', schema=None) as batch_op:
        batch_op.drop_column('player1_power')

    # ### end Alembic commands ###
