"""empty message

Revision ID: e595180e3e2b
Revises: 338df913cbf6
Create Date: 2021-08-21 16:13:03.192007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e595180e3e2b'
down_revision = '338df913cbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('intellect', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('shild', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('health', sa.Integer(), nullable=False))
        batch_op.drop_column('stat_intellect')
        batch_op.drop_column('stat_health')
        batch_op.drop_column('stat_strength')
        batch_op.drop_column('stat_shild')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stat_shild', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('stat_strength', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('stat_health', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('stat_intellect', sa.INTEGER(), nullable=False))
        batch_op.drop_column('health')
        batch_op.drop_column('shild')
        batch_op.drop_column('intellect')
        batch_op.drop_column('strength')

    # ### end Alembic commands ###
