"""empty message

Revision ID: f26ce4aee250
Revises: c900b0cd7771
Create Date: 2021-08-18 13:55:43.149011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26ce4aee250'
down_revision = 'c900b0cd7771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneeze_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player2_power', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sneeze_game', schema=None) as batch_op:
        batch_op.drop_column('player2_power')

    # ### end Alembic commands ###
